In [5]:
import pyquil.quil as pq 
import numpy as np
import pyquil.forest as forest
from scipy.linalg import sqrtm

# First we define the new gate from a matrix
x_gate_matrix = np.array(([0.0, 1.0], [1.0, 0.0]))
sqrt_x = sqrtm(x_gate_matrix)
p = pq.Program().defgate("SQRT-X", sqrt_x)

# Then we can use the new gate,
p.inst(("SQRT-X", 0))
print p

DEFGATE SQRT-X:
    0.49999999999999989+0.49999999999999989i, 0.49999999999999989-0.49999999999999989i
    0.49999999999999989-0.49999999999999989i, 0.49999999999999989+0.49999999999999989i

SQRT-X 0



In [20]:
from math import sqrt
print pq.DefGate("TEST", np.array([[sqrt(0.5), sqrt(0.5)],
                                   [-sqrt(0.5) * 1j, sqrt(0.5) * 1j]])).out()

DEFGATE TEST:
    0.70710678118654757+0.0i, 0.70710678118654757+0.0i
    -0.0-0.70710678118654757i, 0.0+0.70710678118654757i



In [7]:
qvm = forest.Connection()
qvm.wavefunction(p)

(array([ 0.5+0.5j,  0.5-0.5j]), [])

In [17]:
non_unitary_mx = (np.array(([1.0, 2.0], [3.0, 4.0])))

print "M: \n", non_unitary_mx
print "Mdagger\n", non_unitary_mx.T.conj()
print "MxMdagger\n", non_unitary_mx.dot(non_unitary_mx.T.conj())
print np.allclose(np.eye(len(non_unitary_mx)), non_unitary_mx.dot(non_unitary_mx.T.conj()))

bad_prog = pq.Program().defgate("NON-UNITARY-BAD-GATE", non_unitary_mx)
bad_prog.inst(("NON-UNITARY-BAD-GATE",0))
bad_prog.inst(("NON-UNITARY-BAD-GATE",1))
print bad_prog
print qvm.wavefunction(bad_prog)

M: 
[[ 1.  2.]
 [ 3.  4.]]
Mdagger
[[ 1.  3.]
 [ 2.  4.]]
MxMdagger
[[  5.  11.]
 [ 11.  25.]]
False
DEFGATE NON-UNITARY-BAD-GATE:
    1.0, 2.0
    3.0, 4.0

NON-UNITARY-BAD-GATE 0
NON-UNITARY-BAD-GATE 1



(array([ 1.+0.j,  3.+0.j,  3.+0.j,  9.+0.j]), [])


In [27]:
import math
1 + math.floor(math.log(6, 2))

3.0